config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  resources :products
  resources :categories, only: [:show]
  
  resources :pages, only: [:show]
  

  
  get 'abouts', to: 'abouts#index'
  post 'products/add_to_cart/:id', to:'application#add_to_cart', as: 'add_to_cart'
  post 'adjust_quantity/:id' => 'application#adjust_quantity', as: 'adjust_quantity'
  delete 'products/remove_from_cart/:id', to:'application#remove_from_cart', as: 'remove_from_cart'
end

app/models/about.rb
class About < ApplicationRecord
    validates :title, :content, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  
  validates :name, presence: true, length: { maximum: 50 }
  # fields: category_id, name
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products
  has_many :products, through: :order_products

  validates :user, presence: true
  # fields: order_id
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :order, :product, presence: true
  # fields: order_id, product_id
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products
  has_many :orders, through: :order_products
  belongs_to :category
  has_one_attached :image

  validates :name, :description, :price, :stock_quantity, :brand, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :stock_quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :name, length: { maximum: 255 }
  validates :brand, length: { maximum: 255 }
  validates :description, length: { maximum: 1000 }
  # fields: product_id, name, description, price, stock_quantity, brand
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index
    @about = About.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :initizalize_session
    before_action :increment_visit_count
    before_action :load_cart

    def add_to_cart
        id = params[:id].to_i
        session[:cart] << id unless session[:cart].include?(id)
        redirect_to root_path
    end

    def remove_from_cart
        session[:cart].delete(params[:id].to_i)
        redirect_to root_path
    end

    def adjust_quantity
       product_id = params[:id].to_i
       quantity = params[:quantity].to_i
       Rails.logger.info "adjust_quantity called with product_id: #{product_id} and quantity: #{quantity}"
       if quantity <= 0
           session[:cart].delete(product_id)
       else
           session[:cart].delete(product_id)
           quantity.times { session[:cart] << product_id }
       end
       redirect_to root_path
   end


    private

    def initizalize_session
        session[:visit_count] ||= 0
        session[:cart] ||= []
    end

    def load_cart
        @cart = Product.find(session[:cart])
    end

    def increment_visit_count
        session[:visit_count] += 1
        @visit_count = session[:visit_count]
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    def create
        products = []

        session[:cart].each do |item|
            product = Product.find(item)
            if !product.nil?
                products << { 
                    price_data: {
                        product_data: {
                            name: product.name,
                            description: product.description
                        },
                        unit_amount: (product.price * 100).to_i,
                        currency: 'cad',
                    },
                    quantity: 1
                }
            end
        end
        
        if products.empty?
            redirect_to root_path
            return
        end
        
        @session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            line_items: products,
            mode: 'payment',
            success_url: checkout_success_url + "?session_id={CHECKOUT_SESSION_ID}",
            cancel_url: checkout_cancel_url
        )

        respond_to do |format|
            format.js
        end
    end

    def success
        @session = Stripe::Checkout::Session.retrieve(params[:session_id])
        @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
        session[:cart] = []
    end

    def cancel
        redirect_to root_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all.pluck(:name)
    @filtered_products = filter_products(params).page(params[:page]).per(20)
  end

  private

  def filter_products(params)
    products = Product.all

    if params[:search].present?
      products = products.where("products.name LIKE ?", "%#{params[:search]}%")
    end

    if params[:min_price].present?
      products = products.where("price >= ?", params[:min_price])
    end

    if params[:max_price].present?
      products = products.where("price <= ?", params[:max_price])
    end

    if params[:recently_modified].present?
      products = products.where("updated_at >= ?", 3.days.ago)
    end

    if params[:recently_created].present?
      products = products.where("created_at >= ?", 3.days.ago)
    end

    if params[:on_sale].present?
      products = products.where(on_sale: true)
    end

    if params[:category].present? && params[:category] != 'Select a category'
      products = products.joins(:category).where(categories: { name: params[:category] })
    end

    products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
        def sign_up_params
        params.require(:user).permit(:email, :password, :password_confirmation, :province, :address)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/abouts/index.html.erb
<div class="row g-4">
  <div class="col-lg-8">
    <% @about.each do |about| %>
      <div class="mb-4">
        <h2 class="display-4 fw-bold mb-3 text-primary"><%= about.title %></h2>
        <p class="lead text-muted"><%= about.content %></p>
      </div>
    <% end %>
  </div>
  <div class="col-lg-4">
    <img src="https://res.cloudinary.com/practicaldev/image/fetch/s--jvDLhx0b--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/i/cpcr5w0kgl6j94tss7n9.png" alt="image" class="img-fluid rounded-3 shadow-lg mb-4">
    <h2 class="display-5 fw-bold mb-3 text-success">Contact</h2>
    <div class="card shadow-sm">
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item bg-light"><strong>Name:</strong> Samanpreet Kaur</li>
          <li class="list-group-item bg-light"><strong>Email:</strong> samanpreetakaur@academic.rrc.ca</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center"><%= @category.name %></h1>

<div class="row pt-3">
  <% @category.products.each do |product| %>
    <div class="col-md-3 pb-3">
      <div class="card h-100">
        <div class="card-body d-flex flex-column justify-content-between">
          <%= image_tag(product.image, alt: product.name) if product.image.present? %>
          <div class="pt-3">
            <h5 class="card-title text-info text-uppercase">
              <%= link_to product.name, product_path(product), class: "text-decoration-none" %>
            </h5>
            <p class="card-text text-dark"><%= product.description %></p>
            <p class="card-text"><small class="text-muted">Sold by: <%= product.brand %></small></p>
            <p class="card-text"><small class="text-muted">Stock: <%= product.stock_quantity %></small></p>
          </div>
          <div class="d-flex justify-content-between mt-auto pt-3">
            <% if @cart.include?(product) %>
              <div><%= button_to 'remove from cart', remove_from_cart_path(product.id), method: :delete %></div>
            <% else %>
              <div><%= button_to 'add to cart', add_to_cart_path(product.id), method: :post %></div>
            <% end %>
            <h5 class="mb-3"><%= number_to_currency(product.price) %></h5>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/checkout/create.js.erb
const stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');
stripe.redirectToCheckout({
sessionId: '<%= @session.id %>'
}).then(function(result) {
console.log(result.error.message);
});

app/views/checkout/success.html.erb
<h1>Your Order Was Successful!</h1>

<%= debug @session %>
<%= debug @payment_intent %>

app/views/home/index.html.erb
<form class="d-flex w-100 pb-3" role="search" method="get" action="<%= root_path %>">
  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
  <input class="form-control me-2" type="number" placeholder="Min Price" aria-label="Min Price" name="min_price">
  <input class="form-control me-2" type="number" placeholder="Max Price" aria-label="Max Price" name="max_price">
  <div class="form-check me-2">
    <input class="form-check-input" type="checkbox" value="1" id="on_sale" name="on_sale">
    <label class="form-check-label" for="on_sale">
      On Sale
    </label>
  </div>
  <div class="form-check me-2">
    <input class="form-check-input" type="checkbox" value="1" id="recently_modified" name="recently_modified">
    <label class="form-check-label" for="recently_modified">
      Recently Modified
    </label>
  </div>
  <div class="form-check me-2">
    <input class="form-check-input" type="checkbox" value="1" id="recently_created" name="recently_created">
    <label class="form-check-label" for="recently_created">
      Created At
    </label>
  </div>
  <%= select_tag 'category', options_for_select(@categories.unshift('Select a category'), params[:category]), class: 'form-control me-2' %>
  <button class="btn btn-outline-success" type="submit">Search</button>
</form>
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Shopping Cart
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <% if @cart.empty? %>
          <p>You have no items</p>
        <% else %>
          <% @cart.each do |product| %>
            <div class="row pb-2">
              <div class="col-8 d-flex justify-content-between align-items-center">
                <span><%= product.name %> - $<%= product.price %></span>
                <%= form_with(url: adjust_quantity_path(product.id), method: :post, local: true, class: 'd-flex align-items-center gap-3')  do |form| %>
                  <span>Quantity: <%= session[:cart].count(product.id) %></span>
                  <%= form.number_field :quantity, value: session[:cart].count(product.id), min: 0, class: 'form-control' %>
                  <%= form.submit 'Update Quantity', class: 'btn btn-info' %>
                <% end %>
              </div>
              <div class="col-4 d-flex justify-content-end">
                <%= button_to 'remove from cart', remove_from_cart_path(product.id), method: :delete, class: 'btn btn-danger' %>
              </div>
            </div>
          <% end %>
        <% end %>
        <%= button_to "Checkout", checkout_create_path, class: 'btn btn-success', id: 'checkoutButton' %>
      </div>
    </div>
  </div>
</div>
<div class="row pt-3">
  <% @filtered_products.each do |product| %>
    <div class="col-md-3 pb-3">
      <div class="card h-100">
        <div class="card-body d-flex flex-column justify-content-between">
          <%= image_tag(product.image, alt: product.name) if product.image.present? %>
          <div class="pt-3">
            <h5 class="card-title text-info text-uppercase">
              <%= link_to product.name, product_path(product), class: "text-decoration-none" %>
            </h5>
            <p class="card-text text-dark"><%= product.description %></p>
            <p class="card-text"><small class="text-muted">Sold by: <%= product.brand %></small></p>
            <p class="card-text"><small class="text-muted">Stock: <%= product.stock_quantity %></small></p>
          </div>
          <div class="d-flex justify-content-between mt-auto pt-3">
            <% if @cart.include?(product) %>
              <div><%= button_to 'remove from cart', remove_from_cart_path(product.id), method: :delete, class: 'btn btn-warning' %></div>
            <% else %>
              <div><%= button_to 'add to cart', add_to_cart_path(product.id), method: :post, class: 'btn btn-primary' %></div>
            <% end %>
            <h5 class="mb-3"><%= number_to_currency(product.price) %></h5>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="pagination justify-content-center mb-5">
  <%= paginate @filtered_products, theme: 'bootstrap-5' %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark custom-navbar fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Welcome Here </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/abouts">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/admin">Admin</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<style>
  /* Custom Navbar Styles */
  .custom-navbar {
    background-color: #4e73df; /* Custom background color */
    border-bottom: 2px solid #2e59d9; /* Optional: Adding a border at the bottom */
  }

  .navbar-dark .navbar-nav .nav-link {
    color: white; /* Navbar link color */
  }

  .navbar-dark .navbar-nav .nav-link.active,
  .navbar-dark .navbar-nav .nav-link:hover {
    color: #ffdf00; /* Hover or active link color */
  }

  .navbar-dark .navbar-brand {
    color: #ffdf00; /* Brand link color */
  }

  .navbar-dark .navbar-toggler-icon {
    background-color: #ffdf00; /* Toggler icon color */
  }

  .navbar-dark .navbar-toggler {
    border-color: #ffdf00; /* Border color of toggler */
  }

  /* Add padding and change font size */
  .navbar {
    padding: 1rem 2rem;
    font-size: 1.1rem;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E-Commerce Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://js.stripe.com/v3/"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= javascript_include_tag 'checkout' %>
    <%= render 'layouts/navbar' %>
    <div class="container" style="margin-top: 50px;">
      <div class="pt-5">
        <p> You have visited <%= pluralize @visit_count, 'times' %></p>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_product.html.erb
<div class="d-flex justify-content-center">
  <div class="card col-md-6">
    <div class="card-body d-flex flex-column justify-content-between">
      <%= image_tag(@product.image, alt: @product.name) if @product.image.present? %>
      <h1 class="card-title"><%= @product.name %></h1>
      <p class="card-text"><%= @product.description %></p>
      <p class="card-text"><%= link_to @product.category.name, category_path(@product.category), class: 'text-decoration-none fw-bold' %></p>
      <p class="card-text"><small class="text-muted">Sold by: <%= @product.brand %></small></p>
      <p class="card-text"><small class="text-muted">Stock: <%= @product.stock_quantity %></small></p>
      <h3><%= number_to_currency(@product.price) %></h3>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<%= render partial: "product", locals: { product: @product } %>